[versions]
agp = "8.6.1"
kotlin = "2.0.0"
hilt = "2.51.1"
accompanist = "0.34.0"
androidxLifecycle = "2.8.7"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.10.0" }

# ui bundle
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2025.01.01" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version = "2.8.6" }
androidx-compose-window = { group = "androidx.compose.material3", name = "material3-window-size-class", version = "1.3.1" }

# accompanist bundle
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-webview = { group = "com.google.accompanist", name = "accompanist-webview", version.ref = "accompanist" }
accompanist-pager-layouts = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-flowlayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "accompanist" }

# androidx bundle
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version = "1.10.0" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.15.0" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version = "1.0.1" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore", version = "1.1.2" }
androidx-palette = { group = "androidx.palette", name = "palette-ktx", version = "1.0.0" }
androidx-hilt = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.2.0" }
android-material = { group = "com.google.android.material", name = "material", version = "1.12.0" }

# androidxLifecycle bundle
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }

# dependencyInjection bundle
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
javaxInject = { group = "javax.inject", name = "javax.inject", version = "1" }

# protobuf bundle
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version = "1.7.1" }

# core bundle
material-kolor = { group = "com.materialkolor", name = "material-kolor", version = "1.7.0" }
android-svg = { group = "com.caverock", name = "androidsvg-aar", version = "1.4" }
boringssl = { group = "io.github.vvb2060.ndk", name = "boringssl", version = "4.0" }
coil-base = { group = "io.coil-kt", name = "coil-base", version = "2.7.0" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version = "2.7.0" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version = "2.7.0" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version = "2.7.0" }
tabler-icon = { group = "io.github.lyxnx.compose.ui", name = "tabler-icons-android", version = "3.29.0" }

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }
lsparanoid = {id = "org.lsposed.lsparanoid", version = "0.6.0" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.0.0-1.0.22" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
sentry = { id = "io.sentry.android.gradle", version = "4.14.1" }

[bundles]
androidxCompose = [
    "androidx-compose-bom",
    "androidx-compose-ui",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
    "androidx-compose-foundation",
    "androidx-compose-window",
    "androidx-activity-compose",
    "androidx-compose-navigation",
    "androidx-compose-animation",
]

accompanist = [
    "accompanist-permissions",
    "accompanist-systemuicontroller",
    "accompanist-webview",
    "accompanist-pager-layouts",
    "accompanist-pager-indicators",
    "accompanist-flowlayout",
]

androidx = [
    "androidx-appcompat",
    "androidx-activity-ktx",
    "androidx-core-ktx",
    "androidx-core-splashscreen",
    "androidx-datastore-core",
    "androidx-palette",
    "android-material",
    "androidx-hilt",
]

androidxLifecycle = [
    "androidx-lifecycle-livedata-ktx",
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-service",
    "androidx-lifecycle-viewModel-compose",
]

dependencyInjection = [
    "hilt-android",
    "javaxInject",
]

protobuf = [
    "kotlinx-serialization-protobuf",
]

core = [
    "material-kolor",
    "android-svg",
    "boringssl",
    "coil-base",
    "coil-compose",
    "coil-svg",
    "coil-gif",
    "tabler-icon",
]